services:
  development:
    image: py-node-dev
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5001:5001"
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: tail -f /dev/null
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - db-pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
volumes:
  db-pgdata:
